import Head from 'next/head';
import Image from 'next/image';
import {Inter} from '@next/font/google';
import styles from '@/styles/Home.module.scss';
import {DailyTasks} from "@/components/dailytasks/dailyTasks";
import {useState} from "react";
import {WeeklyTasks} from "@/components/weeklytasks/weeklytasks";

const inter = Inter({subsets: ['latin']});

export default function Home() {

    const [active, setActive] = useState("DailyTasks")

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className={styles.content}>
                <div className={styles.taskbar}>
                    <button onClick={()=> setActive("DailyTasks")}>Daily Tasks</button>
                    <button onClick={()=> setActive("WeeklyTasks")}>Weekly Tasks</button>
                    <button onClick={()=> setActive("MonthlyTasks")}>Monthly Tasks</button>
                </div>

                <div className={styles.taskBody}>
                    {active === "DailyTasks" && <DailyTasks/>}
                    {active === "WeeklyTasks" && <WeeklyTasks/>}

                </div>
            </div>

        </>
    );
}
